CREATE DATABASE healthcare;
USE healthcare;

SELECT * FROM appointments_sheet;

SELECT * FROM billing_sheet;

SELECT * FROM doctors_sheet;

SELECT * FROM patients_sheet;

SELECT * FROM treatments_sheet;


ALTER TABLE appointments_sheet
RENAME COLUMN `ï»¿appointment_id` TO appointment_id;

ALTER TABLE billing_sheet
RENAME COLUMN `ï»¿bill_id` TO bill_id;

ALTER TABLE doctors_sheet
RENAME COLUMN `ï»¿doctor_id` TO doctor_id;

ALTER TABLE patients_sheet
RENAME COLUMN `ï»¿patient_id` TO patient_id;

ALTER TABLE treatments_sheet
RENAME COLUMN `ï»¿treatment_id` TO treatment_id;


-- Q1. How many patients are registered in the hospital?

SELECT COUNT( patient_id) AS total_registered_patients
FROM patients_sheet;

-- Q2. How many doctors are working in the hospital?

SELECT COUNT( doctor_id) AS total_doctors
FROM doctors_sheet;

-- Q3. What is the total number of appointments?

SELECT COUNT( appointment_id) AS total_appointments
FROM appointments_sheet;


-- Q4. How many appointments were completed, cancelled, or no-show?

SELECT status, COUNT(*) AS total_count
FROM appointments_sheet
GROUP BY status;


-- Q5. What is the gender distribution of patients?

SELECT gender, COUNT(*) AS total_count
FROM patients_sheet
GROUP BY gender;

-- Q6. What is the average patient age?

SELECT  ROUND(AVG(age),0) AS Avg_age
FROM patients_sheet;

-- Q7. Which payment methods are most commonly used?

SELECT payment_method, COUNT(*) AS total_count
FROM billing_sheet
GROUP BY payment_method
ORDER BY total_count DESC;

-- Q8. What is the total revenue generated (Paid bills only)?

SELECT SUM(amount) AS total_revenue
FROM billing_sheet
WHERE payment_status = 'Paid';

-- Q9. How many bills are pending vs completed vs failed?

SELECT payment_status, COUNT(*) AS total_count
FROM billing_sheet
GROUP BY payment_status;

-- Q10. What is the average cost of treatments?

SELECT  treatment_type, ROUND(AVG(cost),2) AS Avg_cost
FROM treatments_sheet
GROUP BY treatment_type
ORDER BY Avg_cost DESC;

-- Q11. Which doctor handled the most appointments?

SELECT d.`Full name`, d.doctor_id, COUNT(a. appointment_id) AS Total_appointment
FROM appointments_sheet a
JOIN doctors_sheet d
ON a.doctor_id = d.doctor_id
GROUP BY d.`Full name`, d.doctor_id
ORDER BY Total_appointment DESC
LIMIT 1;

-- Q12. How many patients visited each doctor?

SELECT d.`Full name`, d.doctor_id, COUNT(DISTINCT a. patient_id) AS Total_patients
FROM appointments_sheet a
JOIN doctors_sheet d
ON a.doctor_id = d.doctor_id
GROUP BY d.`Full name`, d.doctor_id
ORDER BY Total_patients DESC;

-- Q13. What is the monthly trend of appointments?

SELECT 
    MONTH(STR_TO_DATE(appointment_date, '%Y-%m-%d')) AS month,
    COUNT(*) AS total_appointments
FROM appointments_sheet
WHERE appointment_date IS NOT NULL
GROUP BY month
ORDER BY month;

-- Q14. What is the average treatment cost by treatment type?

SELECT treatment_type, ROUND(AVG(cost),2) AS Avg_cost
FROM treatments_sheet
GROUP BY treatment_type
ORDER BY Avg_cost DESC;


-- Q15. Which hospital branch has the most doctors?

SELECT hospital_branch, COUNT(*) AS Total_doctors
FROM doctors_sheet
GROUP BY hospital_branch
ORDER BY Total_doctors DESC;

-- Q16. How many appointments did each specialization handle?

SELECT d.specialization, COUNT(a. appointment_id) AS Total_appoitnments
FROM appointments_sheet a
JOIN doctors_sheet d
ON a.doctor_id = d.doctor_id
GROUP BY d.specialization
ORDER BY Total_appoitnments DESC;


-- Q17. Which treatment type was performed the most?

SELECT treatment_type, COUNT(*) AS treatment_count
FROM treatments_sheet
GROUP BY treatment_type
ORDER BY treatment_count DESC
LIMIT 1;

-- Q18. How many patients visited multiple times?

SELECT `Full Name`,COUNT(patient_id) as total_Visit
FROM patients_sheet
GROUP BY `Full Name`
ORDER BY total_visit DESC
LIMIT 10;

-- Q19. Which city/branch has the highest number of patients?

SELECT d.hospital_branch, COUNT(a.patient_id) AS patient_count
FROM appointments_sheet a
JOIN doctors_sheet d
ON a.doctor_id = d.doctor_id
GROUP BY d.hospital_branch
ORDER BY patient_count DESC;


-- Q20. What is the revenue generated by each payment method?

SELECT payment_method,  SUM(amount) AS total_revenue
FROM billing_sheet
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Q21. Who are the top 5 patients by total spending?

SELECT `Full name`,SUM(amount) as Total_Amount
FROM patients_sheet
JOIN billing_sheet
ON patients_sheet.patient_id=billing_sheet.patient_id
GROUP BY `Full name`
ORDER BY Total_Amount DESC
LIMIT 5;

-- Q22. Which doctor generated the highest revenue?

SELECT d.`Full name` AS doctor_name, SUM(b.amount) AS total_revenue
FROM doctors_sheet d
JOIN appointments_sheet a
  ON d.doctor_id = a.doctor_id        
JOIN billing_sheet b
  ON a.patient_id = b.patient_id
WHERE b.payment_status = 'Paid'
GROUP BY d.`Full name`
ORDER BY total_revenue DESC
LIMIT 1;

-- Q23. Which doctor-specialization combination contributes the most revenue?

SELECT d.`Full name` AS doctor_name, d.specialization, SUM(b.amount) AS total_revenue
FROM billing_sheet b
JOIN appointments_sheet a
  ON b.patient_id = a.patient_id         
JOIN doctors_sheet d
  ON a.doctor_id = d.doctor_id
  WHERE b.payment_status = 'Paid'
GROUP BY d.`Full name` , d.specialization
ORDER BY total_revenue DESC
LIMIT 1;

-- Q24. Which branch contributes the highest overall revenue?

SELECT d.hospital_branch, SUM(b.amount) AS total_revenue
FROM billing_sheet b
JOIN appointments_sheet a
  ON b.patient_id = a.patient_id         
JOIN doctors_sheet d
  ON a.doctor_id = d.doctor_id
  WHERE b.payment_status = 'Paid'
GROUP BY d.hospital_branch
ORDER BY total_revenue DESC
LIMIT 1;

-- Q25. What is the average revenue per patient?

SELECT p.`Full Name`, ROUND(AVG(amount),2) AS Avg_revenue
FROM patients_sheet p
JOIN billing_sheet b
ON p.patient_id = b.patient_id
GROUP BY p.`Full Name`
ORDER BY Avg_revenue;

-- Q26. Which month had the highest revenue?

SELECT 
MONTH(STR_TO_DATE(appointment_date, '%Y-%m-%d')) AS month,
sum(amount) AS total_Revenue
FROM appointments_sheet a
join billing_sheet b
on a.patient_id = b.patient_id
GROUP BY month
ORDER BY month DESC
limit 1;

-- Q27. Which treatment type generated the most revenue?

SELECT t.treatment_id, SUM(b.amount) AS total_revenue
FROM billing_sheet b
JOIN treatments_sheet t
ON b.treatment_id = t.treatment_id
GROUP BY t.treatment_id
ORDER BY total_revenue DESC
LIMIT 1;















